### ISSUE TITLE
GUI bug in startDate

### ISSUE THREAD

**Issue by bsmmoon** [cs2103aug2015-w11-2c/DoLah#133]
It gets endDate as startDate.

ex. `from 25.10.15 to 30.10.15` returns `30.10.15` as startDate and `30.10.15` as endDate.

**Comment by 9gix** [comment]
@bsmmoon I'm closing this as invalid. I have tested in my local machine works correctly for both `master` and `enhance/parser_v0.3` branches. Please reopen the issues if you confirm the bug. (perhaps provide a full scenario and also highlight the `calendar.yaml` file generated by the command)

**Comment by 9gix** [comment]
@bsmmoon I couldn't remember how this issue happened during our tutorial. Could you elaborate the scenario how this could happened?

**Comment by bsmmoon** [comment]
`study week from 9th to 16th`

The begin date will be displayed as 16th as well. The database contains correct entry.

**Comment by bsmmoon** [comment]
@9gix  It was a bug in GUI part.

**Comment by 9gix** [comment]
@bsmmoon Thanks.
