### ISSUE TITLE
calendar method to sort tasks by tags

### ISSUE THREAD

**Issue by eatedcookie** [cs2103aug2015-w11-2c/DoLah#144]
preferrably return a 2d array with a list of tasks in each tag.
for GUI display purposes.

**Comment by bsmmoon** [comment]
Is it sort by tags or search by tags?

On Friday we decided that the main task list will auto-sorted. Does it resolve this issue?

**Comment by eatedcookie** [comment]
@bsmmoon no need alrdy coz we decided to replace it with search
