### ISSUE TITLE
Calendar Presentation

### ISSUE THREAD

**Issue by 9gix** [cs2103aug2015-w11-2c/DoLah#154]
- [ ] GUI Done Page will call Done Task List from calendar View
- [ ] GUI Search Page will call Searched Task List from Caleder View
- [ ] GUI Main Page will call Sorted Task List from Calendar View

Consider using Observer Pattern (PUBSUB)

**Comment by bsmmoon** [comment]
Come to think of it we just need to add task array for search result and use `getSearchedResult()` at GUI like the way `taskList` and `doneList` is handled right now.
