### ISSUE TITLE
client component

### ISSUE THREAD

**Issue by eatedcookie** [cs2103aug2015-w11-2c/DoLah#63]
- [x] DoLahClient
- [x] CalendarInvoker

**Comment by bsmmoon** [comment]
where is the CalendarInvoker you made? I will take over this issue.

**Comment by 9gix** [comment]
@bsmmoon please refer to PR #45 which may be relevant to continue.

**Comment by eatedcookie** [comment]
i think it's in sprint v0.1, not sure if eugene changed it.
the original is in my branch, which eugene has alrdy linked^ :)

**Comment by 9gix** [comment]
@bsmmoon I'm working on it now.

**Comment by 9gix** [comment]
The client component is completed and merged into master. However I lose track on which PR it is. I'll close this issue for now.
