### ISSUE TITLE
Parse event

### ISSUE THREAD

**Issue by bsmmoon** [cs2103aug2015-w11-2c/DoLah#73]

**Comment by bsmmoon** [comment]
a17c7da2a5539bb2038e3f6b0e3c2d54d1942ef7

**Comment by 9gix** [comment]
@bsmmoon so currently parser only creates `FloatingTask` object, I guess this issues refer to the creation of `EventTask` if the format matches. Am I correct?

And there should be one more issues to create `DeadlineTask`?
