### ISSUE TITLE
Handle CommandParseException in GUI

### ISSUE THREAD

**Issue by bsmmoon** [cs2103aug2015-w11-2c/DoLah#77]
Parser will throw invalid_argument more various invalid inputs.

It needs to be handled by whoever calling parser such as DoLahClient.

**Comment by 9gix** [comment]
@eatedcookie please catch and handle the `invalid_argument`. Possibly with a message box.

**Comment by eatedcookie** [comment]
simple handling done in PR #108 
can close this when merged with master?

**Comment by 9gix** [comment]
@eatedcookie you can do it automatically by referring the **Issue No.** inside the **PR description** with a special syntax like "this closes #XXX", then when the PR merged it will automatically close. Please see the example that I have made in your PR.
