### ISSUE TITLE
Fix Calendar Bug

### ISSUE THREAD

**Issue by bsmmoon** [cs2103aug2015-w11-2c/DoLah#79]
Calendar is passed down by copy, and thus calendar at DoLahClient is not changing at all.

**Comment by bsmmoon** [comment]
Use the fix/calendar branch for bug fix.

**Comment by bsmmoon** [comment]
Considering implementing Singleton pattern since calendar perfectly fit that description.

**Comment by bsmmoon** [comment]
Closed by mistake.....

**Comment by 9gix** [comment]
I have mentioned this before. Have we tried to pass calendar as reference?

@starkipraggy I think I have discussed this to you earlier to provide setCalendar with calendar argument passed by reference instead of value or pointer.

**Comment by bsmmoon** [comment]
I tried but could not get things done for some reason. Please feel free to try it yourself. You can branch from feature/CLI to start from where I was.

**Comment by bsmmoon** [comment]
But please do asap. Contact me on whatsapp if I don't respond on git since whatsapp alert is more obvious.
