### ISSUE TITLE
Parser format collection

### ISSUE THREAD

**Issue by bsmmoon** [cs2103aug2015-w11-2c/DoLah#94]
plz keep feeding me different formats so that I can try to include them

**Comment by bsmmoon** [comment]
cs2103 on 21-10-2015

**Comment by 9gix** [comment]
add task on 12 jan 2015
add task on 12 january 2015
add task on 12/1/2015
add task on 12/01/2015
add task on 12-01-2015
add task on 12-1-2015
add task on 12 jan
add task on 12 january

**Comment by 9gix** [comment]
add task from <date> until <date>
add task from <date> to <date>
add task between <date> and <date>

**Comment by bsmmoon** [comment]
- [ ] add task on 12 jan 15

**Comment by bsmmoon** [comment]
add task by 12 jan 15

**Comment by bsmmoon** [comment]
- [ ] by Sunday, 11 October 2015
- [ ] on Saturday 17 October

**Comment by bsmmoon** [comment]
- [x] from 6pm to 8pm
- [x] between tuesday 6pm to 8pm
- [x] from tuesday 10pm ~ 2am
